language: cpp
compiler: 
    - gcc
notifications:
    email: false
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/julianightlies -y
    - sudo apt-get update -qq -y
    - sudo apt-get upgrade -qq -y
    - sudo apt-get install julia
    - git config --global user.name "Travis User"
    - git config --global user.email "travis@example.net"
script:
    - julia -e "Pkg.init()"
    - mkdir -p ~/.julia/ZMQ
    - cp -R ./* ~/.julia/ZMQ/
    - julia ~/.julia/ZMQ/test/ZMQ.jl
